# Site settings
title: 
header-img: img/home-bg.png
email: pcherian10@gmail.com
copyright_name: pcherian10
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  pcherian10
learn_profile: pcherian10
email_username: pcherian10@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
